[default.extend-words]
monitord = "monitord"

# All exceptions below should be removed when upstream will be fixed
includeSytem = "includeSytem"
Sytem = "Sytem"
cssPsuedoElementExclusion = "cssPsuedoElementExclusion"
Psuedo = "Psuedo"
criterias = "criterias"
